# Generated by Django 3.1.7 on 2021-12-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_carecenter_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='CareCenter_Head_a',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Company_staff_1_a',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Company_staff_2_a',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Company_staff_3_a',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_CareCenter_a',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_doctor_a',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
