# Generated by Django 3.1.7 on 2022-01-03 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carecenter', '0008_auto_20211228_1902'),
        ('users', '0003_auto_20211222_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment_table',
            name='CareCenter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carecenter.carecenter'),
            preserve_default=False,
        ),
    ]
