# Generated by Django 3.1.7 on 2022-01-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_appointment_table_carecenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment_table',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='prescription_receipts'),
        ),
    ]
