# Generated by Django 3.1.7 on 2021-12-19 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatModel',
        ),
    ]
