# Generated by Django 3.1.7 on 2021-12-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carecenter', '0002_carecenter_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carecenter_employee',
            name='employee_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='employee_pics'),
        ),
    ]
