# Generated by Django 3.1.7 on 2021-12-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carecenter', '0003_auto_20211221_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='carecenter_employee',
            name='Address',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
