# Generated by Django 3.1.7 on 2021-12-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carecenter', '0006_auto_20211221_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='carecenter_employee',
            name='About',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='carecenter_employee',
            name='Job_role',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
